### ISSUE TITLE
Plot speed vs y-position (and x-position)

### ISSUE THREAD

**Issue by maxshafer** [annnic/cichlid-analysis#3]
Adding Quantitative measurements to run_combine_als.

Plot speed vs position as scatter plot. Can be either all smoothed data points, or data points from the average day.

**Comment by maxshafer** [comment]
We could do something like this for either each individual, or for all individuals combined

https://python-graph-gallery.com/1136-2/

**Comment by annnic** [comment]
Discussed and we chose a scatter plot of speed vs y position both binned by 30min to give the average relationship.
