### ISSUE TITLE
'retracking' doesn't work if split tracking files exist in directory

### ISSUE THREAD

**Issue by maxshafer** [annnic/cichlid-analysis#8]
Running 'retracking' on all videos (track all videos "y") errors out if run on a folder where 'split_tracking' has already been run (removing the new background images, and the 'cleaned' csvs solves this issue).

This behaviour makes sense, 'split_tracking' would have to be re-done on the retracked videos (if necessary). Solution might be for manual deletion of these files, or 'exclude' annotation to be added as a first step of 'retracking' if they exist? I am manually moving them to another location now.

> /usr/local/bin/python3.7 /Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/retracking.py
Update background? y/n: 
n
Track videos? y/n: 
y
Track all videos? y/n: 
y
objc[7265]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9fcb03c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x129f47f50). One of the two will be used. Which one is undefined.
Track with another roi? y/n: 
y
/Volumes/BZ/Scientific Data/RG-AS04-Data01/Cichlid_sleep_videos/FISH20200930_LT_Cyplep/20200930_c1_Cyprichromis-leptosoma/roi_file.yaml
{'cam_ID': '19463369', 'roi_0': (118, 114, 576, 816), 'roi_1': (688, 97, 544, 848)}
Traceback (most recent call last):
  File "/Users/maxwellshafer/cichlid-analysis/cichlidanalysis/tracking/retracking.py", line 115, in <module>
    curr_roi[2]]
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1'

**Comment by annnic** [comment]
Thanks! Let me know if there's any more troubles
